### ISSUE TITLE
Missing Libs

### ISSUE THREAD

**Issue by azacchino** [podonoghue/usbdm-hcs08#1]
@podonoghue 

This file missing on proyect load by Altium 
`USBDM_SWD_SER_JS16CWJ.IntLib`

And this file (MyLibrary.IntLib) are used in several components and fail to link. 
	
Thanks for this great proyect

**Comment by podonoghue** [comment]
Hi,

You should be able to use the project without the libraries.
The direct reference to USBDM_SWD_SER_JS16CWJ.IntLib was accidental and will be removed.
You can produce a library of all components used on the board from the menu item **Design->Make integrated Library**

MyLibrary.IntLib contains many unrelated items and is a bit big to include if not needed.
